### ISSUE TITLE
Lab Enhancement

### ISSUE THREAD

**Issue by squidprogram** [nahiyanbhuiyan2001/lab-08-Bhuiyan-Nahiyan#1]
Your code is working fine and I pulled the original inImage.pgm so now I have all the parts. I'm just going to add another function that cuts the image in half so you end up with two left sides of the image.

**Comment by nahiyanbhuiyan2001** [comment]
ok, sounds good!

**Comment by squidprogram** [comment]
I have pushed the code up and created a pull request. Thanks!
